name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev build-essential git ffmpeg libsdl2-dev
        pip install buildozer

    - name: Init buildozer
      run: buildozer init

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: bin/*.apk
